// Generated by CoffeeScript 1.7.1
var coffee, concat, connect, gulp, imagemin, jade, less, livereload, minifyCss, rimraf, rjs, rjsReplace, runSequence, uglify, usemin, watch;

gulp = require("gulp");

coffee = require("gulp-coffee");

rjs = require("gulp-requirejs");

rimraf = require("rimraf");

jade = require("gulp-jade");

less = require("gulp-less");

watch = require("gulp-watch");

livereload = require("gulp-livereload");

runSequence = require("run-sequence");

connect = require("gulp-connect");

imagemin = require("gulp-imagemin");

concat = require("gulp-concat");

minifyCss = require("gulp-minify-css");

uglify = require("gulp-uglify");

usemin = require("gulp-usemin");

rjsReplace = require("gulp-requirejs-replace-script");

gulp.task("clean", function(done) {
  return rimraf("dist", done);
});

gulp.task("copy-assets", function() {
  return gulp.src("src/assets/**/*").pipe(gulp.dest("dist"));
});

gulp.task("coffee", function() {
  return gulp.src("src/coffee/**/*.coffee").pipe(coffee({
    bare: true
  })).pipe(gulp.dest("dist/js"));
});

gulp.task("optimized-js", ["copy-assets", "coffee"], function() {
  return rjs({
    baseUrl: "dist/js",
    name: "app",
    out: "app-all.js",
    paths: {
      jquery: "../bower_components/jquery2/jquery",
      bootstrap: "../bower_components/bootstrap/dist/js/bootstrap"
    },
    shim: {
      jquery: {
        exports: "jQuery"
      },
      bootstrap: {
        deps: ["jquery"]
      }
    }
  }).pipe(uglify()).pipe(gulp.dest("dist/js"));
});

gulp.task("jade", function() {
  return gulp.src("src/jade/*.jade").pipe(jade()).pipe(gulp.dest("dist"));
});

gulp.task("production-jade", function() {
  return gulp.src("src/jade/*.jade").pipe(jade({
    locals: {
      env: "production"
    }
  })).pipe(gulp.dest("dist"));
});

gulp.task("less", function() {
  return gulp.src("src/less/app.less").pipe(less()).pipe(gulp.dest("dist/css"));
});

gulp.task("imagemin", function() {
  return gulp.src("src/assets/img/**/*").pipe(imagemin()).pipe(gulp.dest("dist/img"));
});

gulp.task("usemin", ["production-jade"], function() {
  return gulp.src("dist/*.html").pipe(usemin({
    css: ["concat", minifyCss()]
  })).pipe(gulp.dest("dist"));
});

gulp.task("build-development", function() {
  return runSequence("clean", ["copy-assets", "coffee", "jade", "less"]);
});

gulp.task("build-production", function() {
  return runSequence("clean", ["copy-assets", "coffee", "optimized-js", "jade", "less", "imagemin", "usemin", "copy-assets-for-production"]);
});

gulp.task("copy-assets-for-production", ["copy-assets"], function() {
  return gulp.src(["dist/bower_components/bootstrap/dist/fonts/*", "dist/bower_components/fontawesome/fonts/*"]).pipe(gulp.dest("dist/fonts"));
});

gulp.task("development-watch-server", function() {
  connect.server({
    root: "dist",
    livereload: true
  });
  watch({
    name: "assets",
    glob: "src/assets/**/*"
  }).pipe(gulp.dest("dist"));
  watch({
    name: "coffee",
    glob: "src/coffee/**/*.coffee"
  }).pipe(coffee({
    bare: true
  })).pipe(gulp.dest("dist/js"));
  watch({
    name: "less",
    glob: "src/less/**/*.less"
  }).pipe(less()).pipe(gulp.dest("dist/css"));
  watch({
    name: "jade",
    glob: "src/jade/*.jade"
  }).pipe(jade()).pipe(gulp.dest("dist"));
  return watch({
    name: "dist",
    glob: "dist/**"
  }).pipe(connect.reload());
});

gulp.task("production-server", ["build-production"], function() {
  return connect.server({
    root: "dist",
    livereload: false
  });
});

gulp.task("default", function() {
  return gulp.start("development-watch-server");
});
